### ISSUE TITLE
Error on build with iPad

### ISSUE THREAD

**Issue by forksofpower** [bolav/fuse-datepicker#1]
I encountered this error when attempting to build the example on and iPad (iOS 9.1).

```
Preview detected an unhandled exception: Uno.Exception: DatePickerImpl must have a native parent view. Theme provides no native view for parent type iOSDatePicker
   at Fuse.iOS.NativeViews.NativeView.RootNativeView()
   at Fuse.iOS.NativeViews.NativeView.OnRooted(Fuse.Node)
   at Fuse.Behavior.Rooted(Fuse.Node)
   at Fuse.Node.RootBehaviors()
   at Fuse.Node.Root()
   at Fuse.Node.Root()
   at Fuse.Node.Root()
   at Fuse.Node.Root()
   at Fuse.Node.RootChild(Fuse.Node)
   at Fuse.Controls.ParentControl.ListChildAdded(Fuse.Node)
   at Uno.Collections.ObservableList`1.Add(T)
   at Outracks.Simulator.FakeApp.set_RootNode(Fuse.Node)
   at Uno.Reflection.CppFunction.Invoke(object,object[])
   at Outracks.Simulator.Reflection.Native.TryInvokeExtension.TryInvoke(Uno.Reflection.IFunction,object,object[])
   at Outracks.Simulator.Reflection.Native.NativeReflection.SetPropertyValue(object,Outracks.Simulator.Bytecode.TypeMemberName,object)
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.WriteProperty)
   at Outracks.Simulator.Bytecode.Expression.Match`1(Uno.Func<Outracks.Simulator.Bytecode.ReadVariable, T>,Uno.Func<Outracks.Simulator.Bytecode.Literal, T>,Uno.Func<Outracks.Simulator.Bytecode.Lambda, T>,Uno.Func<Outracks.Simulator.Bytecode.MethodGroup, T>,Uno.Func<Outracks.Simulator.Bytecode.IsType, T>,Uno.Func<Outracks.Simulator.Bytecode.LogicalOr, T>,Uno.Func<Outracks.Simulator.Bytecode.Instantiate, T>,Uno.Func<Outracks.Simulator.Bytecode.CallLambda, T>,Uno.Func<Outracks.Simulator.Bytecode.CallStaticMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.CallDynamicMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadStaticField, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.WriteProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.AddEventHandler, T>,Uno.Func<Outracks.Simulator.Bytecode.RemoveEventHandler, T>)
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.Expression)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Uno.Collections.IEnumerable<Outracks.Simulator.Bytecode.Statement>)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Outracks.Simulator.Bytecode.Lambda,object[])
   at Outracks.Simulator.Runtime.LambdaClosure.Func(object)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(object,object[])
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.CallLambda)
   at Outracks.Simulator.Bytecode.Expression.Match`1(Uno.Func<Outracks.Simulator.Bytecode.ReadVariable, T>,Uno.Func<Outracks.Simulator.Bytecode.Literal, T>,Uno.Func<Outracks.Simulator.Bytecode.Lambda, T>,Uno.Func<Outracks.Simulator.Bytecode.MethodGroup, T>,Uno.Func<Outracks.Simulator.Bytecode.IsType, T>,Uno.Func<Outracks.Simulator.Bytecode.LogicalOr, T>,Uno.Func<Outracks.Simulator.Bytecode.Instantiate, T>,Uno.Func<Outracks.Simulator.Bytecode.CallLambda, T>,Uno.Func<Outracks.Simulator.Bytecode.CallStaticMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.CallDynamicMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadStaticField, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.WriteProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.AddEventHandler, T>,Uno.Func<Outracks.Simulator.Bytecode.RemoveEventHandler, T>)
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.Expression)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Uno.Collections.IEnumerable<Outracks.Simulator.Bytecode.Statement>)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Outracks.Simulator.Bytecode.Lambda,object[])
   at Outracks.Simulator.Runtime.LambdaClosure.Func(object)
   at Outracks.Simulator.Runtime.LambdaClosure.Action(object)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(object,object[])
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.CallLambda)
   at Outracks.Simulator.Bytecode.Expression.Match`1(Uno.Func<Outracks.Simulator.Bytecode.ReadVariable, T>,Uno.Func<Outracks.Simulator.Bytecode.Literal, T>,Uno.Func<Outracks.Simulator.Bytecode.Lambda, T>,Uno.Func<Outracks.Simulator.Bytecode.MethodGroup, T>,Uno.Func<Outracks.Simulator.Bytecode.IsType, T>,Uno.Func<Outracks.Simulator.Bytecode.LogicalOr, T>,Uno.Func<Outracks.Simulator.Bytecode.Instantiate, T>,Uno.Func<Outracks.Simulator.Bytecode.CallLambda, T>,Uno.Func<Outracks.Simulator.Bytecode.CallStaticMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.CallDynamicMethod, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadStaticField, T>,Uno.Func<Outracks.Simulator.Bytecode.ReadProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.WriteProperty, T>,Uno.Func<Outracks.Simulator.Bytecode.AddEventHandler, T>,Uno.Func<Outracks.Simulator.Bytecode.RemoveEventHandler, T>)
   at Outracks.Simulator.Runtime.ScopeClosure.Evaluate(Outracks.Simulator.Bytecode.Expression)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Uno.Collections.IEnumerable<Outracks.Simulator.Bytecode.Statement>)
   at Outracks.Simulator.Runtime.ScopeClosure.Execute(Outracks.Simulator.Bytecode.Lambda,object[])
   at Outracks.Simulator.Runtime.VirtualMachine.Execute(Outracks.Simulator.Runtime.IReflection,Outracks.Simulator.Bytecode.Lambda,object[])
   at Outracks.Simulator.Runtime.VirtualMachine.Execute(Outracks.Simulator.Bytecode.Lambda,object[])
   at Outracks.Simulator.Reifying.OnEnterState()
   at Outracks.Simulator.Application.SetState(Outracks.Simulator.State)
   at Outracks.Simulator.Application.OnUpdate()
   at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
   at Uno.Platform2.Display.OnTick(Uno.Platform.TimerEventArgs)

Preview detected an unhandled exception: Uno.AggregateException: One or more errors occurred.
   at Fuse.UpdateManager.Update(Fuse.Stage)
   at Fuse.UpdateManager.Update()
   at Fuse.AppBase.OnUpdate()
   at Fuse.App.OnUpdate()
   at Outracks.Simulator.Application.OnUpdate()
   at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
   at Uno.Platform2.Display.OnTick(Uno.Platform.TimerEventArgs)
```

**Comment by bolav** [comment]
Is this still a problem?
